### ISSUE TITLE
Custom token format

### ISSUE THREAD

**Issue by TheCycoONE** [andywilsonuk/StringTokenFormatter#1]
Hello,

For my use case the unformatted string can be entered by the user. We use PHP like tokens e.g. ${Name}.

It looks like it would be pretty easy to modify your library to allow custom token identifier formats. Is this something you would consider?

**Comment by andywilsonuk** [comment]
Hi,

Just looking at the code that seems like a good change.

I'll start working on the code; what I'm thinking is that you can pass a concrete implementation of an interface that defines the tokens, escape characters etc and I'll add some tests in for an alternative set of markers like ${Name}.

Watch this space!
Andy

**Comment by TheCycoONE** [comment]
Spiffy, I will!

**Comment by andywilsonuk** [comment]
Hi,

v1.6 is out of the door.

Please let me if you get any issues; essentially you want to implement TokenMarkers you pass that to TokenReplacer.

Andy

**Comment by TheCycoONE** [comment]
Works well for me! It would be nice, but not critical, to be able to pass the custom TokenMarkers class to the extension methods as well.

**Comment by andywilsonuk** [comment]
Yeah I thought about it but there are already so many overloads. You can always add an extension method in your project if you're using it a lot.

Andy
