### ISSUE TITLE
Slow performance and high CPU usage

### ISSUE THREAD

**Issue by DanAvni** [andywilsonuk/StringTokenFormatter#10]
Hi Andy

I was trying to figure out some high CPU usage on my PC when I discovered that for a specific input the regex used to identify tokens takes over a minute to execute. I created some test code using the code from DefaultTokenMatcher and saw that if I add to the regex the compiled option I can save 30 seconds but still it takes over 30 seconds to complete for a string that only contains 3 tokens.
I did notice that the regex is trying to capture the token and everything before and after it. and that if I change the regex to not capture the text before and after the token it runs in about 1ms

I attach a text file with the contents of the problematic string

Any ideas?

[SlowPerformance.txt](https://github.com/andywilsonuk/StringTokenFormatter/files/2775272/SlowPerformance.txt)

**Comment by andywilsonuk** [comment]
Hi Dan,

Nothing immediately unfortunately, I'll have a play around and see what I can find out. 

Thanks for the sample text.

Andy

**Comment by andywilsonuk** [comment]
Hi Dan,

I've rewritten the token matching logic and sorted out the performance issues; a test using your sample text which executed at <20ms!

Can you check out version 2.0.8 and let me know if you see the performance improvements?

Cheers
Andy

**Comment by DanAvni** [comment]
Hi Andy

Many thanks! I have verified it works as expected.
