### ISSUE TITLE
Permission to Update Nuget 

### ISSUE THREAD

**Issue by TonyValenti** [andywilsonuk/StringTokenFormatter#17]
Hi @andywilsonuk ,
I've made a few enhancements and bug fixes to StringTokenFormatter.  Can you grant Tony.Valenti@GMail.com permission to publish updates to the Nuget package?

**Comment by andywilsonuk** [comment]
Hey Tony,

I'll have a quick look at the change. There's a few things to do before we push to nuget, specifically with updating the version number of the dll (can you do that?). 

Busy time of year so it might be a little while before I get a chance to pick this up.

Andy

**Comment by TonyValenti** [comment]
Hi Andy,
I have a handful of other changes that aren’t committed so I’ll get that wrapped in when I bring those in. 

Have a great Christmas!

**Comment by TonyValenti** [comment]
Hi @andywilsonuk -
I wanted to let you know I just did the commit.  If you're interested, I'm using it to do some really cool stuff:
https://www.youtube.com/watch?v=-olAUDQKqPU

**Comment by andywilsonuk** [comment]
Wow, looking good! I like what you're doing with null checking containers and TokenNameComparer. I made just one minor comment. Do you have any other changes for this release?

**Comment by TonyValenti** [comment]
Hi @andywilsonuk ,
I just made the adjustments and checked in the code.  I made one other change that i want to point out:
Previously in one place I apparently had it using the Current Culture as opposed to the invariant culture.  This was actually in error so I adjusted it to be Invariant Culture.  Here's why:

I spend a lot of time reading on the http://www.github.com/dotnet/roslyn, http://www.github.com/dotnet/csharplang and http://www.github.com/dotnet/runtime repositories.  I've seen a number of times when the .NET teams have had issues because they made the mistake of doing things culture specific instead of using the invariant culture.  For one basic example, let's say you have this code:
````
  const string V1 = "Hello World";
  const string V2 = "(((" + V1 +")))";
````
It would be really nice if you could do the following instead (infact, lots of people expect the following to work):
````
  const string V1 = "Hello World";
  const string V2 = $@"((({V1})))";
````
However, it doesn't and cant because they made the mistake of causing string interpolation to use the current culture (which isn't know until runtime) even though pretty much anyone looking at the above would agree that the two snippets _should_ be equivalent and both constants.  I've also seen a number of cases where code seems to work on one person's computer and the exact same code doesn't work on someone else's because of a culture nuance.

Anyway, all that to say, I have found that when it comes to culture, it is best to make people explicitly opt-into culture-awareness so that they understand they are taking those risks.

**Comment by andywilsonuk** [comment]
Great to see the library in action, thanks for sharing it with me.

> Hi @andywilsonuk -
> I wanted to let you know I just did the commit. If you're interested, I'm using it to do some really cool stuff:
> https://www.youtube.com/watch?v=-olAUDQKqPU

**Comment by andywilsonuk** [comment]
I didn't realise that about interpolation, I've always found the current culture/invariant culture thing a bit of a hassle.

**Comment by TonyValenti** [comment]
Hi @andywilsonuk  -
I hope all is well!  Any chance you can give me permission to update the nuget package so I can release these changes?

**Comment by andywilsonuk** [comment]
Hi @TonyValenti been a while. I've updated nuget.org, hopefully you'll get an email soon.
