### ISSUE TITLE
Issue with malformed token

### ISSUE THREAD

**Issue by DanAvni** [andywilsonuk/StringTokenFormatter#2]
On my usage case, my user is going to write the template I will be using. So in theory he can write a malformed token like below which does not replace other tokens in the string
`
Dim s As String = "hello {token your name is {name} it is now {d}"

Dim tokenValues = New Dictionary (Of  String, String) From { { "name", "centre" },{"d",DateTime.Now} }

Dim result = s.FormatToken(tokenValues)
`

the output of this code is
hello {token your name is {name} it is now 07/06/2017 11:22:32

the name token in this case was missed although provided

**Comment by andywilsonuk** [comment]
Hi DanAvni,

It's been a while since I looked at this code but leave it with me and I'll have a look at putting in a fix.

Andy

**Comment by andywilsonuk** [comment]
Hi DanAvni,

I've updated 1.6.1 which should fix this issue.

Andy

**Comment by DanAvni** [comment]
Thanks! will check it next week
