### ISSUE TITLE
Strong name support

### ISSUE THREAD

**Issue by DanAvni** [andywilsonuk/StringTokenFormatter#27]
Trying to upgrade from V4 to V6.1 I see the strong name has was removed. Is this intended?

**Comment by andywilsonuk** [comment]
Hi @DanAvni, yeah I removed it as part of modernizing the library as signed assemblies never really achieved much and whilst officially still exist in .net core, my understanding is that it's no longer something to rely upon.

Is this going to cause you a problem?

**Comment by DanAvni** [comment]
I am able to strong name sign during compilation using Brutal.Dev.StrongNameSigner so not an "issue" but for some applications out there (like mine) that use strong naming we could benefit if all libraries would be strong named out of the box. Up to you as I do have a work around

**Comment by andywilsonuk** [comment]
I'll make sure the sign key is back in the next nuget package.
