### ISSUE TITLE
FrozenDictionaryTokenValueContainer

### ISSUE THREAD

**Issue by TonyValenti** [andywilsonuk/StringTokenFormatter#33]
@andywilsonuk -
Can you add one that conditionally becomes available if the target framework is 8.0 or greater?

FrozenDictionaries are super fast post-construction.

**Comment by andywilsonuk** [comment]
Good shout, I'll check it out.

**Comment by andywilsonuk** [comment]
@TonyValenti I added this in v8 but it's opt in at the moment because from the benchmarks I've seen there's a hit to creating the dictionary and only by re-using the container will the read benefit be realised. Any thoughts on this?

**Comment by TonyValenti** [comment]
Hi Andy,
I haven't looked at V8 yet, but in general, I would recommend having its own container, so I can explicitly choose to use frozen dictionary. You are correct that it is slower, but it is so much faster!

**Comment by andywilsonuk** [comment]
Nothing new has been discovered so I'll close this.
