### ISSUE TITLE
Question: format a property that has a null value?

### ISSUE THREAD

**Issue by rjperes** [andywilsonuk/StringTokenFormatter#40]
How can I add a custom formatter that will be executed for a null property? I would like to replace all/some of my null properties with something like "N/A", is this at all possible? Thanks!

**Comment by andywilsonuk** [comment]
Hi. Yeah you can do that with a [Value Converter](https://github.com/andywilsonuk/StringTokenFormatter?tab=readme-ov-file#value-converters).

Easiest way is to add it as the first converter within the settings, something like:

```
static TryGetResult NullConverter(object? value, string tokenName) => value is null ? TryGetResult.Success("N/A") : default;
var converters = (new TokenValueConverter[] { NullConverter }).Concat(StringTokenFormatterSettings.Default.ValueConverters).ToList();

var customSettings = StringTokenFormatterSettings.Default with {
    ValueConverters = converters
};
```

**Comment by rjperes** [comment]
Thanks a lot, @andywilsonuk! You saved my day! :-)
