### ISSUE TITLE
Feature request: Add support for prefix & suffix for a token

### ISSUE THREAD

**Issue by DanAvni** [andywilsonuk/StringTokenFormatter#5]
I'll describe this using a scenario as it will be simpler to understand:
My user says he wants to receive a message in the general format of
"Task number {TaskNumber} is scheduled for {DueDate:g}"
during runtime, this message could be sent to the user as a SMS or be displayed in a web browser (or both - as the user wants).
as an SMS, the message should be "Task number 8 is scheduled for 11:00" but for the browser, my user expects the 8 to be a hyperlink that will open the task information and the due date to be a hyperlink that will open something else.

Initially I thought about building two dictionaries one with
`TaskNumber=8`
and one with
`TaskNumber=<a href="...">8</a>`

The problem with this approach is that if the user puts formatting on the token that would not work.

After reading your code a bit and thinking what to do, I think the best solution would be if you support a new class of  PrefixValueSuffix in the dicrionary where the PrefixValueSuffix class has 3 properties as the name suggests.

In the ReplaceTokensWithValues method, value would get formatted correctly in the line
`sb.AppendToken(matchIndex + tokenPair.Value);` just like today and just before and after it you could append the prefix and suffix to the result

This effectively allows me to add the token as this
`TaskNumber=new PrefixValueSuffix("<a href=...>",8,"</a>")`

up to here this would allow me to create two dictionaries and format the SMS string with one and the web string with the other. If possible I would also suggest adding a renderPrefixAndSuffix option and that would allow me to effectively create only one dictionary and just call the format message with a different value depending on the target

What do you think?

**Comment by andywilsonuk** [comment]
I think what you are trying to do falls into a formatting category such that: given you have found a token and replaced it with a value, you want to do additional formatting on how it outputs. I initially was thinking you could solve this with a combination of IFormatProvider and ICustomFormatter however there is a problem with that: you wouldn't know whether the 8 (in your example) was supposed to be output as an 8 or as the TaskNumber wrapped in an anchor formatted 8.

I think what is needed is the ability to specify the string token matching logic, the transform logic (token to value), and the format. Whereby the formatter is given the token whose value is to be formatted as well as any IFormatProvider. The matching logic will take the token markers and the transform logic will handle looking up from a dictionary, calling a function or a combination.

If the three components are defined as interfaces which TokenReplacer can take as an overload then this should provide the necessary hooks.

For the issue being discussed here specifically, you would create a class that implements the formatter interface and based on the token you'd format with your prefix and suffix. There's going to have to be a formatter that can work with IFormatProvider so the custom class could inherit from that.

It feels like this approach will work (and greatly enhance the flexibility) so I'm happy to start pulling the code apart.

**Comment by DanAvni** [comment]
Thanks for the quick response! I like the idea and have to see how it fits my current code as I am trying to get to a single point where all tokens are known. Currently I have created a few extension methods on the dictionary that can take various objects and each fills the dictionary with the needed tokens based on the object.
Do you intend to add another overload to Format(IMatchingLogic, ITransform, IFormatter)? I think that would be perfect as one could use your original Format methods or completely override everything (I think you should provide static access to the built-in implementation of each interface so if I don't want to replace the matching logic I can stay with the existing one by using TokenReplacer.DefaultMatchingLogic)

**Comment by andywilsonuk** [comment]
Hello, this should all be implemented now. Let me know if you have any problems.

Having reread issue 4, I need to put in a method to provide the list but I think issue 5 is now complete.

**Comment by DanAvni** [comment]
Will do. I haven't had time to check all your changes yet but hope to do it soon. Thank you!
